# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/hildeb47/proj/ECE1373_GhostSynth/modules/trem/trem/solution1/impl/verilog/trem.xdc

# IP: ip/trem_ap_sitofp_4_no_dsp_32/trem_ap_sitofp_4_no_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==trem_ap_sitofp_4_no_dsp_32 || ORIG_REF_NAME==trem_ap_sitofp_4_no_dsp_32}]

# IP: ip/trem_ap_fdiv_14_no_dsp_32/trem_ap_fdiv_14_no_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==trem_ap_fdiv_14_no_dsp_32 || ORIG_REF_NAME==trem_ap_fdiv_14_no_dsp_32}]

# IP: ip/trem_ap_fmul_2_max_dsp_32/trem_ap_fmul_2_max_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==trem_ap_fmul_2_max_dsp_32 || ORIG_REF_NAME==trem_ap_fmul_2_max_dsp_32}]

# IP: ip/trem_ap_fadd_3_full_dsp_32/trem_ap_fadd_3_full_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==trem_ap_fadd_3_full_dsp_32 || ORIG_REF_NAME==trem_ap_fadd_3_full_dsp_32}]
