# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z100ffg900-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/hildeb47/proj/ECE1373_GhostSynth/modules/trem/trem/solution1/impl/verilog/project.cache/wt [current_project]
set_property parent.project_path /home/hildeb47/proj/ECE1373_GhostSynth/modules/trem/trem/solution1/impl/verilog/project.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/hildeb47/proj/ECE1373_GhostSynth/modules/trem/trem/solution1/impl/verilog/project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/hildeb47/proj/ECE1373_GhostSynth/modules/trem/trem/solution1/impl/verilog/Block_proc.v
  /home/hildeb47/proj/ECE1373_GhostSynth/modules/trem/trem/solution1/impl/verilog/Block_proc4.v
  /home/hildeb47/proj/ECE1373_GhostSynth/modules/trem/trem/solution1/impl/verilog/fifo_w32_d2_A.v
  /home/hildeb47/proj/ECE1373_GhostSynth/modules/trem/trem/solution1/impl/verilog/trem.v
  /home/hildeb47/proj/ECE1373_GhostSynth/modules/trem/trem/solution1/impl/verilog/trem_fadd_32ns_32bkb.v
  /home/hildeb47/proj/ECE1373_GhostSynth/modules/trem/trem/solution1/impl/verilog/trem_fdiv_32ns_32dEe.v
  /home/hildeb47/proj/ECE1373_GhostSynth/modules/trem/trem/solution1/impl/verilog/trem_fmul_32ns_32cud.v
  /home/hildeb47/proj/ECE1373_GhostSynth/modules/trem/trem/solution1/impl/verilog/trem_sitofp_32s_3eOg.v
  /home/hildeb47/proj/ECE1373_GhostSynth/modules/trem/trem/solution1/impl/verilog/tremolo_calculation.v
}
read_ip -quiet /home/hildeb47/proj/ECE1373_GhostSynth/modules/trem/trem/solution1/impl/verilog/project.srcs/sources_1/ip/trem_ap_sitofp_4_no_dsp_32/trem_ap_sitofp_4_no_dsp_32.xci
set_property is_locked true [get_files /home/hildeb47/proj/ECE1373_GhostSynth/modules/trem/trem/solution1/impl/verilog/project.srcs/sources_1/ip/trem_ap_sitofp_4_no_dsp_32/trem_ap_sitofp_4_no_dsp_32.xci]

read_ip -quiet /home/hildeb47/proj/ECE1373_GhostSynth/modules/trem/trem/solution1/impl/verilog/project.srcs/sources_1/ip/trem_ap_fdiv_14_no_dsp_32/trem_ap_fdiv_14_no_dsp_32.xci
set_property is_locked true [get_files /home/hildeb47/proj/ECE1373_GhostSynth/modules/trem/trem/solution1/impl/verilog/project.srcs/sources_1/ip/trem_ap_fdiv_14_no_dsp_32/trem_ap_fdiv_14_no_dsp_32.xci]

read_ip -quiet /home/hildeb47/proj/ECE1373_GhostSynth/modules/trem/trem/solution1/impl/verilog/project.srcs/sources_1/ip/trem_ap_fmul_2_max_dsp_32/trem_ap_fmul_2_max_dsp_32.xci
set_property is_locked true [get_files /home/hildeb47/proj/ECE1373_GhostSynth/modules/trem/trem/solution1/impl/verilog/project.srcs/sources_1/ip/trem_ap_fmul_2_max_dsp_32/trem_ap_fmul_2_max_dsp_32.xci]

read_ip -quiet /home/hildeb47/proj/ECE1373_GhostSynth/modules/trem/trem/solution1/impl/verilog/project.srcs/sources_1/ip/trem_ap_fadd_3_full_dsp_32/trem_ap_fadd_3_full_dsp_32.xci
set_property is_locked true [get_files /home/hildeb47/proj/ECE1373_GhostSynth/modules/trem/trem/solution1/impl/verilog/project.srcs/sources_1/ip/trem_ap_fadd_3_full_dsp_32/trem_ap_fadd_3_full_dsp_32.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/hildeb47/proj/ECE1373_GhostSynth/modules/trem/trem/solution1/impl/verilog/trem.xdc
set_property used_in_implementation false [get_files /home/hildeb47/proj/ECE1373_GhostSynth/modules/trem/trem/solution1/impl/verilog/trem.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top trem -part xc7z100ffg900-1 -no_iobuf -mode out_of_context


write_checkpoint -force -noxdef trem.dcp

catch { report_utilization -file trem_utilization_synth.rpt -pb trem_utilization_synth.pb }
